#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Mar 10 14:29:19 CET 2025
# SW Build 5266912 on Sun Dec 15 09:03:31 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim clk_gate_top_behav -key {Behavioral:sim_1:Functional:clk_gate_top} -tclbatch clk_gate_top.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim clk_gate_top_behav -key {Behavioral:sim_1:Functional:clk_gate_top} -tclbatch clk_gate_top.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

