# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/led_cons.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0/design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_upgraded_ipi_imp_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_gate_top_0_0/design_1_clk_gate_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_gate_top_0_0 || ORIG_REF_NAME==design_1_clk_gate_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0/design_1_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_imem_interface_0_0/design_1_imem_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_imem_interface_0_0 || ORIG_REF_NAME==design_1_imem_interface_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dmem_interface_0_0/design_1_dmem_interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dmem_interface_0_0 || ORIG_REF_NAME==design_1_dmem_interface_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_gate_top_0_1/design_1_clk_gate_top_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_gate_top_0_1 || ORIG_REF_NAME==design_1_clk_gate_top_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_scan_chain_top_0_0/design_1_scan_chain_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_scan_chain_top_0_0 || ORIG_REF_NAME==design_1_scan_chain_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reset_top_0_0/design_1_reset_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reset_top_0_0 || ORIG_REF_NAME==design_1_reset_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dual_clock_bram_0_1/design_1_dual_clock_bram_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dual_clock_bram_0_1 || ORIG_REF_NAME==design_1_dual_clock_bram_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_dual_clock_bram_1_1/design_1_dual_clock_bram_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_dual_clock_bram_1_1 || ORIG_REF_NAME==design_1_dual_clock_bram_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pc_monitor_top_0_0/design_1_pc_monitor_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pc_monitor_top_0_0 || ORIG_REF_NAME==design_1_pc_monitor_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_saa_flt_0_0/design_1_saa_flt_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_saa_flt_0_0 || ORIG_REF_NAME==design_1_saa_flt_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_imp_auto_pc_5/design_1_axi_interconnect_0_imp_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_5 || ORIG_REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_imp_auto_pc_0/design_1_axi_interconnect_0_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_imp_auto_pc_1/design_1_axi_interconnect_0_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_1 || ORIG_REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_imp_auto_pc_2/design_1_axi_interconnect_0_imp_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_2 || ORIG_REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_imp_auto_pc_3/design_1_axi_interconnect_0_imp_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_3 || ORIG_REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_imp_auto_pc_4/design_1_axi_interconnect_0_imp_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_4 || ORIG_REF_NAME==design_1_axi_interconnect_0_imp_auto_pc_4} -quiet] -quiet

# XDC: /home/jhomann/Projects/OpenFLINT/repos/public/OpenFI4ASIC/runtime/vivado/OpenFI4ASICSystem/OpenFI4ASICSystem.gen/sources_1/bd/design_1/design_1_ooc.xdc
